### ISSUE TITLE
[Bug] Too many open files

### ISSUE THREAD

**Issue by Spydrouge** [opencog/unity3d-opencog-game#69]
After running the game for about any length of time, with or without batteries, the opencog back end will print out this:

```
Backtrace:
In ice-9/boot-9.scm:
157: 1 Exception thrown while printing backtrace:
ERROR: in procedure load-objcode: Too many open files

ERROR: in procedure apply-smob/1:
ERROR: in procedure pipe: Too many open files
scm_unprotect_object called on unprotected object
```
And promptly it will hang.

**Comment by brett79** [comment]
Preliminary investigation. Drop a battery, load the robot, watch the robot get the battery, drop another battery, watch the robot get the battery... repeat. The error seems to appear repeatedly around "cycle = 160".
Using the windows unity viewer, and ubuntu in a virtual machine. I 'paused' the unity viewer (alt-tab away from viewer), around 'Cycle=148'.
$ lsof > lsof.log

There seem to be over 10000 entries from 'oac':

$ grep -c oac lsof.log
13908
COMMAND    PID  TID       USER   FD      TYPE             DEVICE SIZE/OFF     NODE NAME
...
oac       3539 3549      bwolf  329w     FIFO                0,8      0t0    62263 pipe
oac       3539 3549      bwolf  330r     FIFO                0,8      0t0    62264 pipe
oac       3539 3549      bwolf  331w     FIFO                0,8      0t0    62264 pipe
oac       3539 3549      bwolf  332r     FIFO                0,8      0t0    62265 pipe
oac       3539 3549      bwolf  333w     FIFO                0,8      0t0    62265 pipe
oac       3539 3549      bwolf  334r     FIFO                0,8      0t0    62266 pipe
...

Just posting this here in case someone with a little more knowledge knows where this may be coming from. I don't believe it is a memory error, but rather 'Too many open files'.
Cheers, BW.

**Comment by linas** [comment]
should open this as a bug report against opencog, instead of the unity game

**Comment by ngeiswei** [comment]
I've copied it there https://github.com/opencog/opencog/issues/1240
